import { Worker } from 'worker_threads'
import { ChildProcess } from 'child_process'
import * as Cluster from 'cluster'

/** This information will be passed to the IPC transport provider when the connect() (or disconnect()) method is called. */
export interface IpcShardIdentificationOptions {
  /** This is a unique identifier generated by the library for each shard, including sharding managers. */
  id: string
  /**
   * This property may be nullable only when the shard tries to connect (or disconnect)
   * to the sharding manager.
   * */
  process?: Cluster.Worker | Worker | ChildProcess
}
